import uuid
from typing import Protocol, List
from app.domain.entities import (
    Document,
    User,
    Job,
    AgentRun,
    DocumentChunk,
    LLMUsage,
    PromptVersion,
    AgentRunStatus,
    JobStatus
)


class UserRepository(Protocol):
    async def create(self, user: User) -> User: ...
    async def get_user_by_email(self, email: str) -> User | None: ...
    async def get_user_by_id(self, user_id: uuid.UUID) -> User | None: ...


class DocumentRepository(Protocol):
    async def create(self, document: Document) -> Document | None: ...
    async def get_file_by_id(self, document_id: uuid.UUID) -> Document | None: ...
    async def get_file_by_hash(self, content_hash: str) -> Document | None: ...
    async def update_status(self, document_id: uuid.UUID, status: str) -> None: ...
    async def update_document_results(self, document_id: uuid.UUID, classification: str | None = None, metadata: str | None = None, summary: str | None = None, risk_analysis: str | None = None) -> None: ...


class FileStorage(Protocol):
    async def upload(self, content: bytes, key: str) -> None: ...
    async def download(self, key: str) -> bytes: ...
    async def delete(self, key: str) -> None: ...


class JobRepository(Protocol):
    async def create_job(self, document_id: uuid.UUID) -> Job: ...
    async def claim_next_job(self) -> Job | None: ...
    async def mark_completed(self, job_id: uuid.UUID) -> None: ...
    async def mark_failed(self, job_id: uuid.UUID, error: str) -> None: ...
    async def update_job_status(self, job_id: uuid.UUID, status: JobStatus, attempts: int) -> None: ...
    async def send_to_dlq(self, job_id: uuid.UUID, document_id: uuid.UUID, error_message: str, stack_trace: str, payload: str | None = None) -> None: ...
    async def reschedule_job(self, job_id: uuid.UUID, attempts: int, delay_seconds: int) -> None: ...


class AgentRunRepository(Protocol):
    async def create_run(self, run: AgentRun) -> AgentRun: ...
    async def update_run_status(self, run_id: uuid.UUID, status: AgentRunStatus, retries: int, error_message: str | None = None) -> None: ...
    async def get_runs_by_document_id(self, document_id: uuid.UUID) -> List[AgentRun]: ...


class LLMProvider(Protocol):
    async def generate(self, prompt: str, system_prompt: str | None = None) -> str: ...
    async def embed(self, text: str) -> List[float]: ...


class DocumentChunkRepository(Protocol):
    async def save_chunks(self, chunks: List[DocumentChunk]) -> None: ...
    async def search_similar_chunks(self, document_id: uuid.UUID, query_embedding: List[float], limit: int = 5) -> List[DocumentChunk]: ...


class LLMUsageRepository(Protocol):
    async def log_usage(self, usage: LLMUsage) -> None: ...
    async def get_usage_metrics(self) -> dict: ...


class PromptRepository(Protocol):
    async def get_prompt_by_name(self, name: str) -> PromptVersion | None: ...
    async def create_prompt_version(self, prompt: PromptVersion) -> PromptVersion: ...
